AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'spec/support/**/*'
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
MethodLength:
  Max: 12
Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
